### ISSUE TITLE
出现点问题

### ISSUE THREAD

**Issue by zhangtianqing98** [TheKingOfDuck/ApkAnalyser#1]
![image](https://user-images.githubusercontent.com/56418530/76536540-73093f00-64b7-11ea-9973-33e02a55b0be.png)

表哥，报了这个问题

**Comment by 98Kstar** [comment]
同上。

**Comment by TheKingOfDuck** [comment]
相对路径没处理好，放到程序自动创建的apps目录就好了，我忙过这段时间再重写正则，顺便修这个bug
