### ISSUE TITLE
ApkAnalyser运行问题和可能的漏洞

### ISSUE THREAD

**Issue by Cl0udG0d** [TheKingOfDuck/ApkAnalyser#12]
作者大大 问题如下

## Q1 
apkutils新版本已经不支持初始化的时候传入apkpath
![image](https://github.com/TheKingOfDuck/ApkAnalyser/assets/45556496/d9a8fe10-ccdd-458a-b55c-3866c6ba5a9f)

https://github.com/kin9-0rz/apkutils/blob/master/apkutils/apk.py

![image](https://github.com/TheKingOfDuck/ApkAnalyser/assets/45556496/06107577-2fe2-475c-924f-5631591b3f24)

我把版本降到 0.10.1 才可以运行 ，建议添加 requirements.txt

**Comment by Cl0udG0d** [comment]
## Q2

可能是灯下黑，在验证APK文件名的时候没有校验，可能会导致命令执行，合并到其他扫描工具里面做扫描的时候就会出现问题

![image](https://github.com/TheKingOfDuck/ApkAnalyser/assets/45556496/61e9d25b-a3eb-418e-bb1d-d2ba8d5dde51)

我这里用的easyroot.apk，更新文件名为  source && whoami &&.apk

使用
> python test.py "source && whoami &&.apk"

（这里的python文件我本地文件名改成了test.py，因为一开始没运行起来

![image](https://github.com/TheKingOfDuck/ApkAnalyser/assets/45556496/4841f3d5-ce0a-4492-91e3-1f26e518bd01)

**Comment by TheKingOfDuck** [comment]
Q1:  自己改下不就完了，这脚本我学生时代写完就用过一次，之后再没用过，现在看它写的像坨💩一样。
Q2：多少有点蛋疼，emmmm，怎么说呢，就这垃圾脚本还集成到别的项目里面去？我自己都不用。。。所以就这管他叫漏洞我是很无语的，建议多挖点有意义的洞，少关注这种有的没的。
