### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by 98Kstar** [TheKingOfDuck/ApkAnalyser#2]
+]2020-03-13 10:58:58 running
[?]C:\Users\98Kstar\Desktop\ApkAnalyser-master\ApkAnalyser-master\1.apk
Traceback (most recent call last):
  File "apkAnalyser.py", line 308, in <module>
    apkPath = apkPath.replace("\\", "/")
NameError: name 'apkPath' is not defined
[2412] Failed to execute script apkAnalyser
PS C:\Users\98Kstar\Desktop\ApkAnalyser-master\ApkAnalyser-master>

**Comment by TheKingOfDuck** [comment]
相对路径没处理好，放到程序自动创建的apps目录就好了，我忙过这段时间再重写正则，顺便修这个bug
