### ISSUE TITLE
分析百度文库apk 时自动退出了

### ISSUE THREAD

**Issue by yangweijie** [TheKingOfDuck/ApkAnalyser#3]
rt

**Comment by TheKingOfDuck** [comment]
整catch出来啥的，不然都不知道错误在哪儿

**Comment by yangweijie** [comment]
不知道你日志在哪 你随便下一个最新百度文库apk 试一下就好



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "鸭王"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午3:57
收件人: "TheKingOfDuck/ApkAnalyser"<ApkAnalyser@noreply.github.com&gt;; 
抄送: "杨维杰"<917647288@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [TheKingOfDuck/ApkAnalyser] 分析百度文库apk 时自动退出了 (#3)





 
整catch出来啥的，不然都不知道错误在哪儿
